# Welcome to Jekyll!
title: Fabian Blog
email: #something@domain.tld
description: Blog about the JSVM, scala and others
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fagossa.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: fabgutierr
github_username:  fagossa

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

google-analytics:
  id: 'UA-112314690-1'


